/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.u1a5_jefferylin;

/**
 *
 * @author 342441086
 */
public class AirlinePointsProgram extends javax.swing.JFrame {

    /**
     * Creates new form AirlinePointsProgram
     */
    String[][] theArray = new String[50][6];
    int currentIndex = 0;
    public AirlinePointsProgram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameBox = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameBox = new javax.swing.JTextField();
        testLabel1 = new javax.swing.JLabel();
        weekBox1 = new javax.swing.JTextField();
        weekBox2 = new javax.swing.JTextField();
        testLabel2 = new javax.swing.JLabel();
        weekBox3 = new javax.swing.JTextField();
        testLabel3 = new javax.swing.JLabel();
        weekBox4 = new javax.swing.JTextField();
        testLabel4 = new javax.swing.JLabel();
        listButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayBox = new javax.swing.JTextArea();
        totalPointsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(51, 102, 255));
        titleLabel.setText("Airline Points");

        firstNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstNameLabel.setText("First name:");

        firstNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameBoxActionPerformed(evt);
            }
        });

        lastNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastNameLabel.setText("Last name:");

        lastNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameBoxActionPerformed(evt);
            }
        });

        testLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        testLabel1.setText("Week 1");

        weekBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weekBox1ActionPerformed(evt);
            }
        });

        weekBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weekBox2ActionPerformed(evt);
            }
        });

        testLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        testLabel2.setText("Week 2");

        weekBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weekBox3ActionPerformed(evt);
            }
        });

        testLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        testLabel3.setText("Week 3");

        weekBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weekBox4ActionPerformed(evt);
            }
        });

        testLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        testLabel4.setText("Week 4");

        listButton.setText("List");
        listButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        displayBox.setEditable(false);
        displayBox.setColumns(20);
        displayBox.setRows(5);
        jScrollPane1.setViewportView(displayBox);

        totalPointsButton.setText("Total Points");
        totalPointsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPointsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(firstNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lastNameBox, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(testLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(weekBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(testLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(weekBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(testLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(weekBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(testLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(weekBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listButton)
                            .addComponent(addButton)
                            .addComponent(totalPointsButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(testLabel1)
                            .addComponent(weekBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(testLabel2)
                            .addComponent(weekBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(testLabel3)
                            .addComponent(weekBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(testLabel4)
                            .addComponent(weekBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(addButton)
                        .addGap(18, 18, 18)
                        .addComponent(listButton)
                        .addGap(18, 18, 18)
                        .addComponent(totalPointsButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameBoxActionPerformed

    private void lastNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameBoxActionPerformed

    private void weekBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weekBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weekBox1ActionPerformed

    private void weekBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weekBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weekBox2ActionPerformed

    private void weekBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weekBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weekBox3ActionPerformed

    private void weekBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weekBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weekBox4ActionPerformed

    private void listButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listButtonActionPerformed
        // TODO add your handling code here:
        displayBox.setText("");
        String output = "First name\tLast name\tWeek 1\tWeek 2\tWeek 3\tWeek 4\t";
        for (int i = 0; i<currentIndex; i++) {
            output += "\n----------------------------------------------------------------------------------------------------------------------------\n";
            for (int j = 0; j<6; j++) {
               output += theArray[i][j];
               output += "\t";
            }
        }
        displayBox.setText(output);
    }//GEN-LAST:event_listButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        displayBox.setText("");
        boolean inArray = false, isInt = true, isEmpty = false, isPositive = true;
        String firstName = "", lastName = "";
        int week1, week2, week3, week4;
        int[] weeks = new int[4];
        firstName = firstNameBox.getText();
        lastName = lastNameBox.getText();
        for (int i = 0; i<currentIndex; i++) {
            if (theArray[i][0].equals(firstName)) {
                if (theArray[i][1].equals(lastName)) {
                    inArray = true;
                }
            }
        }
        if (firstName.trim().isEmpty() || lastName.trim().isEmpty()) {
            isEmpty = true;
        }
        try {
            weeks[0] = Integer.parseInt(weekBox1.getText());
            weeks[1] = Integer.parseInt(weekBox2.getText());
            weeks[2] = Integer.parseInt(weekBox3.getText());
            weeks[3] = Integer.parseInt(weekBox4.getText());
            isInt = true;
        }
        catch (NumberFormatException e){
            displayBox.setText("You must enter an integer for the points");
            isInt = false;
        }
        for (int i = 0; i<4; i++) {
            if (weeks[i] < 0) {
                isPositive = false;
                break;
            }
        }
        if (inArray == false) {
            if (isEmpty == false) {
                if (isInt == true) {
                    if (currentIndex < 50) {
                        if (isPositive == true) {
                            System.out.println("added");
                            theArray[currentIndex][0] = firstNameBox.getText();
                            theArray[currentIndex][1] = lastNameBox.getText();
                            theArray[currentIndex][2] = weekBox1.getText();
                            theArray[currentIndex][3] = weekBox2.getText();
                            theArray[currentIndex][4] = weekBox3.getText();
                            theArray[currentIndex][5] = weekBox4.getText();
                            System.out.println(currentIndex);
                            currentIndex++;
                        }
                        else {
                            displayBox.setText("Enter a positive number");
                        }
                    }
                    else {
                        displayBox.setText("Max passengers");
                    }
                }
            }
            else {
                displayBox.setText("You left a required piece of information empty");
            }
        }
        else {
            displayBox.setText("Passenger already exists");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void totalPointsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPointsButtonActionPerformed
        // TODO add your handling code here:
        displayBox.setText("");
        String firstName, lastName;
        int index = 0, total = 0, bonus = 0;
        boolean inArray = false;
        firstName = firstNameBox.getText();
        lastName = lastNameBox.getText();
        for (int i = 0; i<currentIndex; i++) {
            if (theArray[i][0].equals(firstName)) {
                if (theArray[i][1].equals(lastName)) {
                    inArray = true;
                    index = i;
                }
            }
        }
        if (inArray == true) {
            for (int i=2; i<6; i++) {
                total += Integer.parseInt(theArray[index][i]);
            }
            if (total > 5000) {
                bonus = 1000;
            }
            displayBox.setText(firstName + "'s total points are: " + total + "\tBonus: " + bonus);
        }
        else {
            displayBox.setText("Passenger is not in system");
        }
    }//GEN-LAST:event_totalPointsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirlinePointsProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirlinePointsProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirlinePointsProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirlinePointsProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AirlinePointsProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextArea displayBox;
    private javax.swing.JTextField firstNameBox;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameBox;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton listButton;
    private javax.swing.JLabel testLabel1;
    private javax.swing.JLabel testLabel2;
    private javax.swing.JLabel testLabel3;
    private javax.swing.JLabel testLabel4;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton totalPointsButton;
    private javax.swing.JTextField weekBox1;
    private javax.swing.JTextField weekBox2;
    private javax.swing.JTextField weekBox3;
    private javax.swing.JTextField weekBox4;
    // End of variables declaration//GEN-END:variables
}
